name: Build the Android App and upload to Google Play Store

permissions:
  contents: read

on:
  push:
    branches:
      - main
      - prod

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-play-store:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"

    steps:
      - uses: actions/checkout@v7

      - name: Set Up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Set up Keystore
        run: |
          echo "$KEYSTORE_BASE64" | base64 -d > ./release-key.jks
        env:
          KEYSTORE_BASE64: ${{ secrets.SIGNING_KEY }}

      - name: Create keystore.properties
        run: |
          echo "storeFile=release-key.jks" > keystore.properties
          echo "storePassword=${{ secrets.KEY_STORE_PASSWORD }}" >> keystore.properties
          echo "keyAlias=${{ secrets.ALIAS }}" >> keystore.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> keystore.properties

      - name: Build phone bundle
        run: ./gradlew app:bundleRelease

      - name: Build Wear bundle
        run: ./gradlew wear:bundleRelease

      - name: Smoke test
        run: ./gradlew lint

      - name: Upload phone
        uses: r0adkll/upload-google-play@v1
        if: github.ref_name == 'prod'
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: ca.ilianokokoro.sanda_timer
          releaseFiles: app/build/outputs/bundle/release/*.aab
          tracks: internal
          status: draft

      - name: Upload Wear
        uses: r0adkll/upload-google-play@v1
        if: github.ref_name == 'prod'
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: ca.ilianokokoro.sanda_timer
          releaseFiles: wear/build/outputs/bundle/release/*.aab
          tracks: internal
          status: draft
