name: Build the Android App and upload to Google Play Store

permissions:
  contents: read

on:
  push:
    branches:
      - main
      - prod

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-play-store:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7

      - name: Set Up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Set up Keystore
        run: |
          echo "$KEYSTORE_BASE64" | base64 -d > ./release-key.jks
        env:
          KEYSTORE_BASE64: ${{ secrets.SIGNING_KEY }}

      - name: Create keystore.properties
        run: |
          echo "storeFile=release-key.jks" > keystore.properties
          echo "storePassword=${{ secrets.KEY_STORE_PASSWORD }}" >> keystore.properties
          echo "keyAlias=${{ secrets.ALIAS }}" >> keystore.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> keystore.properties

      - name: Extract version
        id: version
        run: |
          major=$(grep 'versionMajor' build.gradle.kts | grep -o '[0-9]\+')
          minor=$(grep 'versionMinor' build.gradle.kts | grep -o '[0-9]\+')
          patch=$(grep 'versionPatch' build.gradle.kts | grep -o '[0-9]\+')
          echo "version=v$major.$minor.$patch" >> $GITHUB_OUTPUT

      - name: Build phone bundle
        run: ./gradlew app:bundleRelease

      - name: Build Wear bundle
        run: ./gradlew wear:bundleRelease

      - name: Smoke test
        run: ./gradlew lint

      - name: Upload phone
        uses: r0adkll/upload-google-play@v1
        if: github.ref_name == 'prod'
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: ca.ilianokokoro.sanda_timer
          releaseFiles: app/build/outputs/bundle/release/*.aab
          releaseName: ${{ steps.version.outputs.version }}
          whatsNewDirectory: fastlane/metadata/android/en-CA/whats-new/phone
          tracks: "Android closed beta"
          status: draft

      - name: Upload Wear
        uses: r0adkll/upload-google-play@v1
        if: github.ref_name == 'prod'
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: ca.ilianokokoro.sanda_timer
          releaseFiles: wear/build/outputs/bundle/release/*.aab
          releaseName: ${{ steps.version.outputs.version }} WearOS
          whatsNewDirectory: fastlane/metadata/android/en-CA/whats-new/wearos
          tracks: "wear:Wear OS closed beta"
          status: draft

      - name: Create a Release
        uses: ncipollo/release-action@v1
        if: github.ref_name == 'prod'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ steps.version.outputs.version }}
          commit: prod
          allowUpdates: true
          generateReleaseNotes: false
          makeLatest: true
          draft: true
          body: |
            ## Release ${{ steps.version.outputs.version }}

            ### Full Changelog
            https://github.com/ilianoKokoro/sanda-timer/compare/${{ steps.version.outputs.version }}...${{ steps.version.outputs.version }}

            ## Download link

            <a href="https://play.google.com/store/apps/details?id=ca.ilianokokoro.sanda_timer">
            <img src="https://i.postimg.cc/rm90vjNw/5a902dbf7f96951c82922875.png" height="100" alt="Get Sanda Timer on the Google Play Store">
            </a>
